// V-pptx-export — PDF page rasterization → PowerPoint conversion helper.
//
// Pure conversion function: takes a rendered report PDF's raw bytes and
// returns a .pptx Buffer with one slide per PDF page, each page rasterized
// to a full-bleed image. Used ONLY by pptx-render.processor (the on-demand
// "Render to PowerPoint" job) — never invoked from the normal pdf-render
// pipeline.
//
// Rendering stack (verified against current library docs — see 2026-07-06
// pdfjs-dist v6 / @napi-rs/canvas v1 / pptxgenjs v4 API surface):
//   - pdfjs-dist "legacy" Node build (`pdfjs-dist/legacy/build/pdf.mjs`).
//     On import, pdf.js auto-detects Node.js and internally
//     `require("@napi-rs/canvas")` to polyfill `globalThis.DOMMatrix` /
//     `globalThis.Path2D` — required for the renderer to run outside a
//     browser DOM. @napi-rs/canvas ships prebuilt native binaries per
//     platform (including linux-x64-musl for the Alpine worker image) —
//     no native toolchain / build-from-source needed.
//   - Each page is rendered onto an explicit @napi-rs/canvas 2D context at
//     RENDER_SCALE (≈150 DPI equivalent for a 72-DPI PDF page unit), filled
//     with an opaque white background (pdf.js renders onto a transparent
//     canvas, and JPEG has no alpha channel to preserve that transparency),
//     and encoded to JPEG at JPEG_QUALITY via `canvas.encode('jpeg', 85)`.
//     Report pages are photographic map tiles plus text, and PNG's lossless
//     encoding was a poor fit for that content — measured ~5x deck-size
//     reduction (22.5 MB → 4.2 MB on a real 23-page report) at quality 85,
//     visually indistinguishable from PNG at 1:1 zoom on the worst case
//     (dense small table text).
//   - pptxgenjs assembles the deck. A .pptx has ONE presentation-wide slide
//     size (there is no per-slide page size in the OOXML format), so the
//     deck layout is sized to the FIRST page's physical dimensions (in
//     inches, derived from the PDF's own point size — 1pt = 1/72in). Every
//     report generated by this app uses a single paper size for the whole
//     PDF, so this is full-bleed correct for the overwhelmingly common
//     case. If a later page's aspect ratio differs from the first page
//     (not expected in practice, but not assumed away either), that page's
//     image is CONTAIN-fit and centered within the fixed slide rather than
//     stretched/distorted.
//
// cMap / standard-font data (needed for pdf.js to substitute glyphs for
// non-embedded fonts, e.g. certain CJK ranges) is wired in on a strict
// best-effort basis: resolved from the installed pdfjs-dist package on
// disk when available (local/dev, or any environment that ships the full
// node_modules tree), and silently omitted otherwise. This is safe because
// the source PDFs are Puppeteer-rendered prints of our own HTML reports,
// which embed full font subsets — the standard/cmap fallback path is a
// rarely-hit edge case, not the common path. See file header on the
// esbuild-bundled production worker image, which does NOT ship the
// pdfjs-dist package directory (only the bundled JS) — cMap resolution
// naturally no-ops there today; copying `cmaps/` + `standard_fonts/` into
// the runner image is a documented follow-up if higher fidelity is ever
// needed for a report with exotic embedded glyphs.

import { createRequire } from "node:module";
import { existsSync } from "node:fs";
import { dirname, join } from "node:path";
import { pathToFileURL } from "node:url";
import { getDocument } from "pdfjs-dist/legacy/build/pdf.mjs";
import { createCanvas } from "@napi-rs/canvas";
import PptxGenJS from "pptxgenjs";

/**
 * Render scale applied to the PDF's native 72-DPI point size. 150/72 ≈
 * 2.083 yields ~150 DPI rasterized pages — sharp enough to read comfortably
 * in PowerPoint at full-screen without producing an unreasonably large
 * deck (a typical 1-3 page A4/Letter report yields a low-single-digit-MB
 * .pptx at this scale).
 */
const RENDER_SCALE = 150 / 72;

/**
 * JPEG quality for rasterized pages. 85 is the measured sweet spot: on a
 * real 23-page map/photo-heavy report it cuts the deck from ~22.5 MB (PNG,
 * lossless) to ~4.2 MB — a ~5x reduction — while remaining visually
 * indistinguishable from PNG at 1:1 zoom on the worst case (dense small
 * table text). Report pages are photographic map tiles plus text; PNG's
 * lossless encoding is a poor fit and was the single biggest size driver.
 */
const JPEG_QUALITY = 85;

/** Points-per-inch — used to convert pdf.js viewport units (already in
 * 72-DPI CSS-pixel-equivalent units) back to a physical inch size for the
 * pptxgenjs slide layout, independent of RENDER_SCALE. */
const POINTS_PER_INCH = 72;

interface RasterizedPage {
  imageBuffer: Buffer;
  /** Physical page size in inches, derived from the PDF's own point size
   * (i.e. independent of RENDER_SCALE — this is the "true" paper size). */
  widthIn: number;
  heightIn: number;
}

/** Best-effort resolution of the installed pdfjs-dist package's bundled
 * cmaps/ + standard_fonts/ directories. Returns undefined values when the
 * package directory is not present on disk (e.g. the slimmed production
 * worker image, which ships only the esbuild-bundled JS) — pdf.js runs
 * fine without these for embedded-font PDFs, which is the only source
 * this helper ever receives (Puppeteer-printed reports). */
function resolveFontResources(): {
  cMapUrl: string | undefined;
  standardFontDataUrl: string | undefined;
} {
  try {
    const require = createRequire(import.meta.url);
    const pkgPath = require.resolve("pdfjs-dist/package.json");
    const pkgRoot = dirname(pkgPath);
    const cMapDir = join(pkgRoot, "cmaps");
    const fontsDir = join(pkgRoot, "standard_fonts");
    return {
      cMapUrl: existsSync(cMapDir)
        ? `${pathToFileURL(cMapDir).href}/`
        : undefined,
      standardFontDataUrl: existsSync(fontsDir)
        ? `${pathToFileURL(fontsDir).href}/`
        : undefined,
    };
  } catch {
    return { cMapUrl: undefined, standardFontDataUrl: undefined };
  }
}

/**
 * Rasterizes every page of a PDF to a PNG buffer + its true physical size
 * (inches). Throws if the PDF cannot be parsed or a page fails to render —
 * the caller (pptx-render.processor) treats any throw as a clean job
 * failure, same posture as a PDF render failure in pdf-render.processor.
 */
async function rasterizePdfPages(pdfBytes: Uint8Array): Promise<RasterizedPage[]> {
  const { cMapUrl, standardFontDataUrl } = resolveFontResources();

  const loadingTask = getDocument({
    data: pdfBytes,
    ...(cMapUrl !== undefined ? { cMapUrl, cMapPacked: true } : {}),
    ...(standardFontDataUrl !== undefined ? { standardFontDataUrl } : {}),
  });

  const pdf = await loadingTask.promise;
  const pages: RasterizedPage[] = [];

  try {
    for (let pageNum = 1; pageNum <= pdf.numPages; pageNum++) {
      const page = await pdf.getPage(pageNum);
      try {
        const renderViewport = page.getViewport({ scale: RENDER_SCALE });
        const canvas = createCanvas(
          Math.ceil(renderViewport.width),
          Math.ceil(renderViewport.height),
        );
        const ctx = canvas.getContext("2d");

        // JPEG has no alpha channel. pdf.js renders onto a TRANSPARENT
        // canvas, so without an explicit opaque fill every page composites
        // to solid black in the encoded JPEG. Report pages are white stock.
        ctx.fillStyle = "#ffffff";
        ctx.fillRect(0, 0, canvas.width, canvas.height);

        const renderTask = page.render({
          // @napi-rs/canvas's 2D context is API-compatible with the
          // CanvasRenderingContext2D shape pdf.js expects.
          canvasContext: ctx as unknown as CanvasRenderingContext2D,
          canvas: canvas as unknown as HTMLCanvasElement,
          viewport: renderViewport,
        });
        await renderTask.promise;

        const imageBuffer = await canvas.encode("jpeg", JPEG_QUALITY);

        // True physical size independent of RENDER_SCALE — the viewport at
        // scale=1 is exactly the PDF's own point size (1pt = 1/72in).
        const baseViewport = page.getViewport({ scale: 1 });
        pages.push({
          imageBuffer,
          widthIn: baseViewport.width / POINTS_PER_INCH,
          heightIn: baseViewport.height / POINTS_PER_INCH,
        });
      } finally {
        page.cleanup();
      }
    }
  } finally {
    // destroy() lives on the loadingTask (not PDFDocumentProxy) — it aborts
    // network requests and tears down the worker thread.
    await loadingTask.destroy();
  }

  if (pages.length === 0) {
    throw new Error("PDF has no pages — cannot render an empty PowerPoint deck");
  }

  return pages;
}

/**
 * Converts a rendered report PDF's raw bytes into a .pptx Buffer — one
 * slide per PDF page, each page rasterized to a full-bleed image sized to
 * the deck's fixed slide layout (derived from the FIRST page's physical
 * size). A page whose own aspect ratio differs from the first page is
 * contain-fit and centered rather than stretched.
 */
export async function renderPdfPagesToPptx(
  pdfBytes: Uint8Array,
): Promise<Buffer> {
  const pages = await rasterizePdfPages(pdfBytes);
  const [firstPage] = pages;
  if (firstPage === undefined) {
    throw new Error("PDF has no pages — cannot render an empty PowerPoint deck");
  }

  const pptx = new PptxGenJS();
  const deckWidthIn = firstPage.widthIn;
  const deckHeightIn = firstPage.heightIn;
  pptx.defineLayout({ name: "REPORT_PDF_PAGE", width: deckWidthIn, height: deckHeightIn });
  pptx.layout = "REPORT_PDF_PAGE";

  for (const page of pages) {
    const slide = pptx.addSlide();
    // Contain-fit + center — a no-op (exact full-bleed 0,0,100%,100%) when
    // this page's aspect matches the deck layout (the common case), and a
    // safe non-distorting fallback when it does not.
    const scale = Math.min(
      deckWidthIn / page.widthIn,
      deckHeightIn / page.heightIn,
    );
    const renderWidthIn = page.widthIn * scale;
    const renderHeightIn = page.heightIn * scale;
    const x = (deckWidthIn - renderWidthIn) / 2;
    const y = (deckHeightIn - renderHeightIn) / 2;

    slide.addImage({
      data: `data:image/jpeg;base64,${page.imageBuffer.toString("base64")}`,
      x,
      y,
      w: renderWidthIn,
      h: renderHeightIn,
    });
  }

  const output = await pptx.write({ outputType: "nodebuffer" });
  return output as Buffer;
}
